# Generated by Django 4.2.4 on 2023-09-09 10:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/About/photos/Image/%Y/%m/%d/')),
                ('Titel', models.CharField(max_length=300, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
                ('Ourmessage', models.CharField(max_length=300, null=True)),
                ('Ourvision', models.CharField(max_length=300, null=True)),
                ('Image2', models.FileField(blank=True, null=True, upload_to='files/images/About/photos/Image/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/Blog/Image/%Y/%m/%d/')),
                ('Titel', models.CharField(max_length=300, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
                ('slideImage', models.FileField(blank=True, null=True, upload_to='files/images/Blog/slideImage/%Y/%m/%d/')),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='businessplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience', models.CharField(max_length=300, null=True)),
                ('CustomSolutions', models.CharField(max_length=300, null=True)),
                ('StrongNetwork', models.CharField(max_length=300, null=True)),
                ('Customers', models.IntegerField(blank=True, default=0, null=True)),
                ('Projects', models.IntegerField(blank=True, default=0, null=True)),
                ('Hours_of_support', models.IntegerField(blank=True, default=0, null=True)),
                ('hard_at_work', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlideImage', models.FileField(blank=True, null=True, upload_to='files/images/Home/Slide/Image/%Y/%m/%d/')),
                ('Map_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('WebName', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
                ('Gmail', models.CharField(blank=True, max_length=300, null=True)),
                ('PHONE', models.CharField(blank=True, max_length=300, null=True)),
                ('Twitterlinke', models.CharField(blank=True, max_length=500, null=True)),
                ('instagramlinke', models.CharField(blank=True, max_length=500, null=True)),
                ('facebooklinke', models.CharField(blank=True, max_length=500, null=True)),
                ('Youtubelinke', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedinlinke', models.CharField(blank=True, max_length=500, null=True)),
                ('Whatsapp', models.CharField(blank=True, max_length=500, null=True)),
                ('snapchat', models.CharField(blank=True, max_length=500, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('OpeningHours', models.CharField(blank=True, max_length=500, null=True)),
                ('pixal_id', models.CharField(blank=True, max_length=500, null=True)),
                ('Copyright', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ourcustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/Reviews/photos/Image/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/Reviews/photos/Image/%Y/%m/%d/')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('jobtitel', models.CharField(max_length=300, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/team/photos/Image/%Y/%m/%d/')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('jobtitel', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
