# Generated by Django 4.2.4 on 2023-09-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Image2',
        ),
        migrations.AddField(
            model_name='service',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/About/photos/Image/%Y/%m/%d/'),
        ),
    ]
