# Generated by Django 4.2.4 on 2023-09-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_remove_about_image2_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/Slide/Image/%Y/%m/%d/')),
                ('Titel', models.CharField(max_length=300, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
                ('Customers', models.IntegerField(blank=True, default=0, null=True)),
                ('Projects', models.IntegerField(blank=True, default=0, null=True)),
                ('team', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Ourmessage',
            new_name='Point1',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Ourvision',
            new_name='Point2',
        ),
        migrations.RenameField(
            model_name='chooseus',
            old_name='hard_at_work',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='information',
            name='OpeningHours',
        ),
        migrations.RemoveField(
            model_name='information',
            name='SlideImage',
        ),
        migrations.AddField(
            model_name='about',
            name='Point3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='Point4',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='Point5',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='FaviconIco',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Home/Information/Image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='information',
            name='LOGO',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Home/Information/Image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='Address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
