# Generated by Django 4.2.4 on 2023-09-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_slide_rename_ourmessage_about_point1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='Image',
            new_name='Image1',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='jobtitel',
        ),
        migrations.AddField(
            model_name='reviews',
            name='Description1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Description2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Description3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Description4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Image2',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Reviews/photos/Image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Image3',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Reviews/photos/Image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Image4',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Reviews/photos/Image/%Y/%m/%d/'),
        ),
    ]
