# Generated by Django 4.2.4 on 2023-09-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='spotlight',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
