# Generated by Django 4.2.4 on 2023-09-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_blog_spotlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Description',
        ),
    ]
