# Generated by Django 4.2.4 on 2023-09-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_categories_blog_keywords_service_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('jobtitel', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='spotlight',
        ),
        migrations.AddField(
            model_name='blog',
            name='slideVideo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
