# Generated by Django 4.2.4 on 2023-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_job_remove_blog_spotlight_blog_slidevideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jobtitel',
            new_name='Jobtitel',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Name',
        ),
        migrations.AddField(
            model_name='job',
            name='Job_type',
            field=models.CharField(choices=[('متاحة', 'متاحة'), ('تم التوظيف', 'تم التوظيف')], default='دوام كامل', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type_available',
            field=models.CharField(choices=[('دوام كامل', 'دوام كامل'), ('دوام جزئي', 'دوام جزئي'), ('غير مذكور', 'غير مذكور')], default='متاحة', max_length=30),
        ),
    ]
