# Generated by Django 4.2.4 on 2023-09-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_rename_jobtitel_job_jobtitel_remove_job_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type_available',
            field=models.CharField(choices=[('دوام كامل', 'دوام كامل'), ('دوام جزئي', 'دوام جزئي'), ('العمل عن بعد', 'العمل عن بعد'), ('غير مذكور', 'غير مذكور')], default='متاحة', max_length=30),
        ),
    ]
