# Generated by Django 4.2.4 on 2023-09-10 14:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_alter_job_job_type_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='slideImage',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Service/slideImage/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='service',
            name='slideVideo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Service/photos/Image/%Y/%m/%d/'),
        ),
    ]
