# Generated by Django 4.2.4 on 2023-09-10 17:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_service_body_service_slideimage_service_slidevideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='Client',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='Image1',
            field=models.FileField(blank=True, null=True, upload_to='files/images/work/photos/Image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='work',
            name='Image2',
            field=models.FileField(blank=True, null=True, upload_to='files/images/work/photos/Image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='work',
            name='Image3',
            field=models.FileField(blank=True, null=True, upload_to='files/images/work/photos/Image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='work',
            name='Image4',
            field=models.FileField(blank=True, null=True, upload_to='files/images/work/photos/Image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='work',
            name='Image5',
            field=models.FileField(blank=True, null=True, upload_to='files/images/work/photos/Image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='work',
            name='Location',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/work/photos/Image/%Y/%m/%d/'),
        ),
    ]
