# Generated by Django 4.2.4 on 2023-09-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_work_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bronze_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Golden_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Silver_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
