# Generated by Django 4.2.4 on 2023-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_bronze_package_golden_package_silver_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Silver_package', models.CharField(max_length=50, null=True)),
                ('Golden_package', models.CharField(max_length=50, null=True)),
                ('Bronze_package', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='Description',
        ),
    ]
