# Generated by Django 4.2.4 on 2023-09-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_pricing_remove_work_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('Description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='information',
            name='Copyright',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='PHONE',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='Whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='pixal_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='snapchat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
