# Generated by Django 4.2.4 on 2023-09-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0018_privacy_policy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Privacy_Policy',
            new_name='Policies',
        ),
    ]
