# Generated by Django 4.2.4 on 2023-09-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0019_rename_privacy_policy_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
