# Generated by Django 4.2.4 on 2023-09-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0020_work_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='businessplan',
        ),
        migrations.DeleteModel(
            name='ChooseUs',
        ),
    ]
